ARDUINO_DIR  = /usr/share/arduino

TARGET       = pingpair
ARDUINO_LIBS = SPI

BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usb*

ARDUINO_PORT =/dev/ttyACM0
ARD_PROG = -c stk500v2

include /usr/share/arduino/Arduino.mk
